apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Python Flask app that displays the time, named ${{ values.app_name }}.
  annotations:
    github.com/project-slug: martindouglasj-org/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental